<?php


echo "		<p><b>Détails des invités</b></p><hr>\n"; 
echo "		<form>\n"; 
echo "		  <div class=\"row\">\n"; 
echo "			<div class=\"large-6 columns\">\n"; 
echo "			  <label class=\"fontcolor\">Prénom*\n"; 
echo "				<input id=\"firstname\" type=\"text\" placeholder=\"\" />\n"; 
echo "			  </label>\n"; 
echo "			</div>\n"; 
echo "			<div class=\"large-6 columns\">\n"; 
echo "			  <label class=\"fontcolor\">Nom*\n"; 
echo "				<input id=\"lastname\" type=\"text\" placeholder=\"\" />\n"; 
echo "			  </label>\n"; 
echo "			</div>\n"; 
echo "		  </div>\n"; 
echo "		  <div class=\"row\">\n"; 
echo "			<div class=\"large-6 columns\">\n"; 
echo "			  <label class=\"fontcolor\"> Addresse e-mail*\n"; 
echo "				<input id=\"email\" type=\"text\" placeholder=\"\" />\n"; 
echo "			  </label>\n"; 
echo "			</div>\n"; 
echo "			<div class=\"large-6 columns\">\n"; 
echo "			  <label class=\"fontcolor\">Téléphone*\n"; 
echo "				<input id=\"phone\" type=\"text\" placeholder=\"\" />\n"; 
echo "			  </label>\n"; 
echo "			</div>\n"; 
echo "		  </div>\n"; 
echo "		  <div class=\"row\">\n"; 
echo "			<div class=\"large-6 columns\">\n"; 
echo "			  <label class=\"fontcolor\">Addresse 1*\n"; 
echo "				<input id=\"addressline1\" type=\"text\" placeholder=\"\" />\n"; 
echo "			  </label>\n"; 
echo "			</div>\n"; 
echo "			<div class=\"large-6 columns\">\n"; 
echo "			  <label class=\"fontcolor\">Addresse 2\n"; 
echo "				<input id=\"addressline2\" type=\"text\" placeholder=\"\" />\n"; 
echo "			  </label>\n"; 
echo "			</div>\n"; 
echo "		  </div>\n"; 
echo "		  <div class=\"row\">\n"; 
echo "			<div class=\"large-6 columns\">\n"; 
echo "			  <label class=\"fontcolor\">Code postal / Zip *\n"; 
echo "				<input id=\"postcode\" type=\"text\" placeholder=\"\" />\n"; 
echo "			  </label>\n"; 
echo "			</div>\n"; 
echo "			<div class=\"large-6 columns\">\n"; 
echo "			  <label class=\"fontcolor\">Ville*\n"; 
echo "				<input id=\"city\" type=\"text\" placeholder=\"\" />\n"; 
echo "			  </label>\n"; 
echo "			</div>\n"; 
echo "		  </div>\n"; 
echo "		  <div class=\"row\">\n"; 
echo "			<div class=\"large-6 columns\">\n"; 
echo "			  <label class=\"fontcolor\">Etat*\n"; 
echo "				<input id=\"state\" type=\"text\" placeholder=\"\" />\n"; 
echo "			  </label>\n"; 
echo "			</div>\n"; 
echo "			<div class=\"large-6 columns\">\n"; 
echo "			  <label class=\"fontcolor\">Pays de résidence *\n"; 
echo "				<input id=\"country\" type=\"text\" placeholder=\"\" />\n"; 
echo "			  </label>\n"; 
echo "			</div>\n"; 
echo "		  </div>\n"; 
echo "		  \n"; 
echo "		  <div class=\"row\">\n"; 
echo "			<div class=\"large-12 columns\">\n"; 
echo "			  <label class=\"fontcolor\">\n"; 
echo "				<textarea id=\"Besoins spéciaux\" placeholder=\"\"></textarea>\n"; 
echo "			  </label>\n"; 
echo "			</div>\n"; 
echo "		  </div>\n"; 
echo "		  <div class=\"row\">\n"; 
echo "			<div class=\"large-12 columns\" >\n"; 
echo "			<div class=\"large-6 columns\"><button type=\"button\" class=\"button small fontslabo\" style=\"background-color:#b7995d;\"  onClick=\"return confirmeverything();\"><a href=\"reservationdetail.php\">Confirm</a></button>\n"; 
echo "			</div>\n"; 
echo "			</div>\n"; 
echo "		  </div>\n"; 
echo "		</form>\n";

?>